name: "publish"

on:
  push:
    branches:
      - main

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin --bundles app"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin --bundles app"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile # change this to npm, pnpm or bun depending on which one you use.

      - name: import Apple Developer certificate
        if: runner.os == 'macOS'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }} # base64-encoded .p12
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PATH: build.keychain

        run: |
          CERT_PATH=$RUNNER_TEMP/certificate.p12
          echo "$APPLE_CERTIFICATE" | base64 --decode > "$CERT_PATH"
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -lut 3600 build.keychain
          security import "$CERT_PATH" -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          # export the identity hash for tauri-action
          CERT_ID=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application" | awk -F'"' '{print $2}')
          echo "APPLE_SIGNING_IDENTITY=$CERT_ID" >> $GITHUB_ENV

      # --- Windows only ---
      - name: Install DigiCert client tools (KSP/SMCTL)
        if: runner.os == 'Windows'
        uses: digicert/ssm-code-signing@v1.1.0

      - name: Write DigiCert client-auth cert (.p12)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          [IO.File]::WriteAllBytes('D:\sm_client_auth.p12',
            [Convert]::FromBase64String('${{ secrets.SM_CLIENT_CERT_FILE_B64 }}'))

      - name: Configure env & sync KeyLocker cert
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          SM_HOST: ${{ secrets.SM_HOST }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_FILE: D:\sm_client_auth.p12
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          KEYPAIR_ALIAS: ${{ secrets.KEYPAIR_ALIAS }}
        run: |
          "SM_HOST=$env:SM_HOST" | Out-File -Append -FilePath $env:GITHUB_ENV
          "SM_API_KEY=$env:SM_API_KEY" | Out-File -Append -FilePath $env:GITHUB_ENV
          "SM_CLIENT_CERT_FILE=$env:SM_CLIENT_CERT_FILE" | Out-File -Append -FilePath $env:GITHUB_ENV
          "SM_CLIENT_CERT_PASSWORD=$env:SM_CLIENT_CERT_PASSWORD" | Out-File -Append -FilePath $env:GITHUB_ENV
          # Bring the cert into CurrentUser\My with a clean sync:
          if ($env:KEYPAIR_ALIAS) {
            smctl windows certsync --keypair-alias "$env:KEYPAIR_ALIAS" --store user --reset
          } else {
            smctl windows certsync --store user --signable --reset
          }

     # Bring the DigiCert certificate into the CurrentUser\My store (fresh each run)
      - name: Sync KeyLocker cert to user store
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          smctl windows certsync --store user --reset

      # Make sure the newest Windows SDK SignTool is discoverable
      - name: Ensure SignTool on PATH
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $binRoot = 'C:\Program Files (x86)\Windows Kits\10\bin'
          $latest = Get-ChildItem $binRoot -Directory | Sort-Object Name -Descending | Select-Object -First 1
          if ($latest) { "$($latest.FullName)\x64" | Out-File -Append -FilePath $env:GITHUB_PATH }

        

      - name: Diagnostics (temporary)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          smctl healthcheck --tools
          smctl keypair ls

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          APPLE_SIGNING_IDENTITY: ${{env.APPLE_SIGNING_IDENTITY}}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}

          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: clean up macOS keychain
        if: runner.os == 'macOS'
        run: security delete-keychain build.keychain

      - name: Verify signatures (optional)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          signtool verify /pa /v "src-tauri/target/release/labric-sync-tauri.exe"
          signtool verify /pa /v "src-tauri/target/release/bundle/msi/Labric Sync_0.1.5_x64_en-US.msi"
          signtool verify /pa /v "src-tauri/target/release/bundle/nsis/Labric Sync_0.1.5_x64-setup.exe"
      